config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"  
  resources :books, only: [:show, :edit, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book = Book.find(params[:id])
  end

  def edit
  end

  def new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books = Book.all.page(params[:page]).per(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="px-5">
<h1>所蔵詳細</h1>
    <table class="table">
    <thead>
        <tr>
        <th scope="col">項目</th>
        <th scope="col">内容</th>

        </tr>
    </thead>
    <tbody>
        <tr>
                <td><label for="bookTitle">タイトル</label></td>
                <td><%= @book.book_title %></td>
            </tr>
            <tr>
                <td><label for="bookPublisher">出版社</label></td>
                <td><%= @book.publisher %></td>
            </tr>
                <tr>
                <td><label for="bookPublicationYear">出版日</label></td>
                <td><%= @book.publication_year %></td>
            </tr>
                <tr>
                <td><label for="bookTitle">書籍コード</label></td>
                <td> <%= @book.bibliographic_id %></td>
            </tr>
                <tr>
                <td><label for="bookTitle">ISBNコード</label></td>
                <td><%= @book.isbn_id %></td>
            </tr>
            <tr>
                <td><label for="bookTitle">価格</label></td>
                <td><%= @book.price %>円</td>
            </tr>
        </tbody>
    </table>
</div>

app/views/home/index.html.erb
<div class="px-5">
	<h1>所蔵一覧</h1>  

	<table class="table">
		<thead>
			<tr>
				<th scope=“col”>タイトル</th>
				<th scope=“col”>著者名</th>
				<th scope=“col”>出版社</th>
				<th scope=“col”>出版日</th>
			</tr>
		</thead>

			<tbody>
			<% @books.each do |book|%>
				<tr>
						<td ><%=link_to book_path(book.id) do %><%= book.book_title %><% end %></td>
						<td><%= book.author_name %></td>
						<td><%= book.publisher %></td>
						<td><%= book.publication_year %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<%= paginate @books, theme: 'bootstrap-5' %>
</div>

app/views/layouts/_header.html.erb
  <header class="top-page">
    <nav class="navbar navbar-expand-md navbar-dark bg-secondary">
        <div class="container"> 
        <%= link_to root_path do %>
            <p class="navbar-brand">ABC図書館</p>
        <% end %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar" aria-controls="Navbar" aria-expanded="false" aria-label="ナビゲーションの切替"> <span class="navbar-toggler-icon"></span> </button>
            <div class="collapse navbar-collapse" id="Navbar">
                <ul class="navbar-nav mr-auto py-3 py-lg-0 mt-3 mt-lg-0">
                    <li class="nav-item"><a class="nav-link" href="#sec1">MENU</a> </li>
                    <li class="nav-item"><a class="nav-link" href="#sec2">MENU</a> </li>
                    <li class="nav-item"><a class="nav-link" href="#sec3">MENU</a> </li>
                    <li class="nav-item"><a class="nav-link" href="#sec4">MENU</a> </li>
                    <li class="nav-item"><a class="nav-link" href="#sec5">MENU</a> </li>
                </ul>
                <div class="text-center text-white pb-2 pb-lg-0"> <a class="btn btn-block btn-outline-light py-3 font-weight-bold" href="contact/index.html" role="button">Webでのご予約はこちら</a> </div>
            </div>
        </div>
    </nav>
</header>
  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibrarySystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <%= yield %>
  </body>
</html>